version: '3.8'

services:
  backend:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8300
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    environment:
      - DEBUG=True
      - SECRET_KEY=test_secret_key
      - DJANGO_ALLOWED_HOSTS=localhost backend
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=panel_back_test
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DATABASE=postgres
      - CORS_ALLOWED_ORIGINS=http://localhost:80,http://localhost
    depends_on:
      - db
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
  
  db:
    image: postgres:16
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=panel_back_test
  
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/app.dev.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/share/nginx/static
      - media_volume:/usr/share/nginx/media
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data_test:
  static_volume:
  media_volume: