version: '3.8'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8300
    volumes:
      - .:/app
    ports:
      - "8300:8300"
    env_file:
      - ./.env.dev
    environment:
      - DATABASE=postgres
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8300/admin/login/" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
  
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=panel_back_dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data: 