# Generated by Django 5.1.6 on 2025-03-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_geographic_area_aqi_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geographicarea',
            name='description',
        ),
    ]
