# Generated by Django 5.1.6 on 2025-04-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_geographicarea_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='address',
        ),
        migrations.AddField(
            model_name='station',
            name='height',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
