# Generated by Django 5.1.6 on 2025-04-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_station_address_station_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
