# Generated by Django 5.1.6 on 2025-04-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_station_height'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParameterType',
            new_name='ParameterName',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='parameter_type',
            new_name='parameter_name',
        ),
    ]
