name: Simple Deployment

on:
  push:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT || '22' }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            
            # Pull latest changes from repository
            git pull
            
            # Make sure helper script is executable
            chmod +x manage-docker.sh
            
            # Deploy based on environment specified in secrets
            DEPLOY_ENV="${{ secrets.DEPLOY_ENVIRONMENT }}"
            
            if [ "$DEPLOY_ENV" = "production" ]; then
              echo "Deploying to production environment..."
              ./manage-docker.sh prod
            elif [ "$DEPLOY_ENV" = "testing" ]; then
              echo "Deploying to testing environment..."
              ./manage-docker.sh test
            else
              echo "Deploying to development environment..."
              ./manage-docker.sh dev
            fi
            
            # Run migrations
            echo "Running migrations..."
            ./manage-docker.sh migrate 